{% set name = "abi3audit" %}
{% set version = "0.0.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pypa/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4cdf4c3f5f3b915435defd014788c037c2c0b11fb50198e87b19176605cb19bb

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true # [py<310]
  entry_points:
    - abi3audit = abi3audit._cli:main

requirements:
  host:
    - flit-core >=3.11,<4
    - python
    - pip
  run:
    - python
    - packaging >=21.3,<26.0
    - pefile >=2022.5.30
    - requests >=2.28.1,<2.33.0
    - requests-cache >=0.9.6,<1.3.0
    - rich >=12.5.1,<14.3.0
    - abi3info >=2024.06.19
    - kaitaistruct >=0.10,<1.0
    - pyelftools >=0.29

test:
  source_files:
    - test
    - pyproject.toml
  imports:
    - abi3audit
  commands:
    - pip check
    - pytest -vv
  requires:
    - pip
    - python
    - pytest

about:
  home: https://pypi.org/project/abi3audit/
  summary: Scans Python wheels for abi3 violations and inconsistencies
  description: |
    abi3audit scans Python extensions for abi3 violations and inconsistencies.
    It can scan individual (unpackaged) shared objects, packaged wheels, or entire package version histories.
  dev_url: https://github.com/pypa/abi3audit
  doc_url: https://github.com/pypa/abi3audit/blob/main/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wshanks
    - BastianZim
